import type { ThemeGroup } from '../core/types';

/**
 * All 90 theme definitions organized in 4 groups.
 * This data drives both the global theme selector and the per-card theme selector.
 */
export const THEME_GROUPS: ThemeGroup[] = [
  {
    label: 'Светлые темы',
    themes: [
      { value: 'default', label: '1. Clean Minimal (Notion / Apple)' },
      { value: 'editorial-paper', label: '2. Editorial Warm Paper' },
      { value: 'pastel-gradient', label: '3. Soft Pastel Gradient' },
      { value: 'fresh-mint', label: '4. Fresh Sage Mint' },
      { value: 'warm-peach', label: '5. Warm Peach Sunset' },
      { value: 'neo-brutalist', label: '6. Neo-Brutalist' },
      { value: 'ocean-breeze', label: '9. Ocean Breeze' },
      { value: 'golden-hour', label: '10. Golden Hour' },
      { value: 'rose-quartz', label: '11. Rose Quartz' },
      { value: 'lavender-dreams', label: '12. Lavender Dreams' },
      { value: 'sandy-beach', label: '13. Sandy Beach' },
      { value: 'spring-meadow', label: '14. Spring Meadow' },
      { value: 'arctic-frost', label: '15. Arctic Frost' },
      { value: 'terracotta-clay', label: '16. Terracotta Clay' },
      { value: 'candy-pop', label: '17. Candy Pop' },
      { value: 'seafoam-mist', label: '18. Seafoam Mist' },
      { value: 'retro-diner', label: '19. Retro Diner' },
      { value: 'blush-nude', label: '20. Blush Nude' },
      { value: 'peach-fuzz', label: '21. Peach Fuzz' },
      { value: 'monochrome-graphite', label: '22. Monochrome Graphite' },
      { value: 'cotton-candy', label: '23. Cotton Candy' },
      { value: 'creamy-vanilla', label: '24. Creamy Vanilla' },
      { value: 'spearmint-fresh', label: '25. Spearmint Fresh' },
      { value: 'vintage-sepia', label: '26. Vintage Sepia' },
      { value: 'aquamarine-dream', label: '27. Aquamarine Dream' },
      { value: 'honey-glaze', label: '28. Honey Glaze' },
      { value: 'nordic-fjord', label: '29. Nordic Fjord' },
      { value: 'coral-reef', label: '30. Coral Reef' },
      { value: 'zen-garden', label: '31. Zen Garden' },
    ],
  },
  {
    label: 'Тёмные темы',
    themes: [
      { value: 'dark-slate', label: '7. Dark Slate Cyan' },
      { value: 'obsidian-gold', label: '8. Obsidian Gold' },
      { value: 'midnight-plum', label: '32. Midnight Plum' },
      { value: 'forest-canopy', label: '33. Forest Canopy' },
      { value: 'charcoal-crimson', label: '34. Charcoal & Crimson' },
      { value: 'electric-violet', label: '35. Electric Violet' },
      { value: 'noir-ink', label: '36. Noir Ink' },
      { value: 'warm-amber', label: '37. Warm Amber' },
      { value: 'slate-blue', label: '38. Slate Blue' },
      { value: 'cyber-lime', label: '39. Cyber Lime' },
      { value: 'sunset-boulevard', label: '40. Sunset Boulevard' },
      { value: 'moss-bark', label: '41. Moss & Bark' },
      { value: 'espresso-shot', label: '42. Espresso Shot' },
      { value: 'electric-blue', label: '43. Electric Blue' },
      { value: 'twilight-violet', label: '44. Twilight Violet' },
      { value: 'plum-velvet', label: '45. Plum Velvet' },
      { value: 'neon-noir', label: '46. Neon Noir' },
      { value: 'galaxy-core', label: '47. Galaxy Core' },
      { value: 'midnight-forest', label: '48. Midnight Forest' },
    ],
  },
  {
    label: 'Градиентные темы',
    themes: [
      { value: 'grad-aurora', label: '49. Aurora' },
      { value: 'grad-sunset-glow', label: '50. Sunset Glow' },
      { value: 'grad-ocean-depth', label: '51. Ocean Depth' },
      { value: 'grad-peach-sorbet', label: '52. Peach Sorbet' },
      { value: 'grad-mint-lagoon', label: '53. Mint Lagoon' },
      { value: 'grad-lavender-mist', label: '54. Lavender Mist' },
      { value: 'grad-golden-sand', label: '55. Golden Sand' },
      { value: 'grad-rose-gold', label: '56. Rose Gold' },
      { value: 'grad-midnight-sky', label: '57. Midnight Sky' },
      { value: 'grad-coral-blaze', label: '58. Coral Blaze' },
      { value: 'grad-forest-mist', label: '59. Forest Mist' },
      { value: 'grad-berry-smoothie', label: '60. Berry Smoothie' },
      { value: 'grad-desert-dawn', label: '61. Desert Dawn' },
      { value: 'grad-glacier', label: '62. Glacier' },
      { value: 'grad-volcanic', label: '63. Volcanic' },
      { value: 'grad-cotton-sky', label: '64. Cotton Sky' },
      { value: 'grad-emerald-night', label: '65. Emerald Night' },
      { value: 'grad-amber-warmth', label: '66. Amber Warmth' },
      { value: 'grad-frost-berry', label: '67. Frost Berry' },
      { value: 'grad-cosmic-dust', label: '68. Cosmic Dust' },
      { value: 'grad-aurora-borealis', label: '69. Aurora Borealis' },
      { value: 'grad-sakura-bloom', label: '70. Sakura Bloom' },
      { value: 'grad-deep-ocean', label: '71. Deep Ocean' },
      { value: 'grad-warm-sunset', label: '72. Warm Sunset' },
      { value: 'grad-northern-lights', label: '73. Northern Lights' },
      { value: 'grad-rose-quartz-dream', label: '74. Rose Quartz Dream' },
      { value: 'grad-amber-glow', label: '75. Amber Glow' },
      { value: 'grad-mint-fresh', label: '76. Mint Fresh' },
      { value: 'grad-twilight-blaze', label: '77. Twilight Blaze' },
      { value: 'grad-ice-crystal', label: '78. Ice Crystal' },
      { value: 'grad-velvet-night', label: '79. Velvet Night' },
      { value: 'grad-citrus-burst', label: '80. Citrus Burst' },
      { value: 'grad-storm-cloud', label: '81. Storm Cloud' },
      { value: 'grad-tropical-paradise', label: '82. Tropical Paradise' },
      { value: 'grad-wine-cellar', label: '83. Wine Cellar' },
      { value: 'grad-frost-morning', label: '84. Frost Morning' },
      { value: 'grad-neon-pulse', label: '85. Neon Pulse' },
      { value: 'grad-earth-tones', label: '86. Earth Tones' },
      { value: 'grad-mystic-forest', label: '87. Mystic Forest' },
      { value: 'grad-pearl-shimmer', label: '88. Pearl Shimmer' },
    ],
  },
  {
    label: 'Без фона',
    themes: [
      { value: 'nobg-dark', label: '89. Тёмный текст (для светлого фона)' },
      { value: 'nobg-light', label: '90. Светлый текст (для тёмного фона)' },
    ],
  },
];
